#!/usr/bin/env bash
# add our scripts and conda path to the default path
echo "export PATH=$HOME/scripts:$HOME/miniconda2/bin:$PATH" >> $HOME/.bashrc
PATH="$HOME/scripts:$HOME/miniconda2/bin:$PATH"

cd $HOME
# download miniconda
curl -L https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh > $HOME/Miniconda2-latest-Linux-x86_64.sh
# install miniconda
bash Miniconda2-latest-Linux-x86_64.sh -b

# install conda packages
conda install -y jupyter
conda install -y ipyparallel
conda install -y scikit-learn
conda install -y keras

# create default ipyparallel profile
ipython profile create --parallel
ipcluster nbextension --user enable
cat >>$HOME/.ipython/profile_default/ipcluster_config.py<<\EOF
c.HubFactory.ip = '*'
c.IPClusterEngines.engine_launcher_class = 'Slurm'
c.IPClusterStart.controller_launcher_class = 'Local'
EOF

mkdir -p $HOME/scripts
# download the ipcluster wrapper script
curl -L https://github.com/psiori/AWS-cluster-config/raw/master/aws-slurm-ipcluster/start_ipcluster > $HOME/scripts/start_ipcluster


