#!/usr/bin/env bash
cd $HOME
# download miniconda
curl -L https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh > $HOME/Miniconda2-latest-Linux-x86_64.sh
# install miniconda
bash Miniconda2-latest-Linux-x86_64.sh -b
# add conda path to the default path
echo "export PATH=$HOME/miniconda2/bin:$PATH" >> $HOME/.bashrc
PATH="$HOME/miniconda2/bin:$PATH"

# install conda packages
conda install -y jupyter
conda install -y ipyparallel
conda install -y scikit-learn
conda install -y keras

# create default ipyparallel profile
ipython profile create --parallel
ipcluster nbextension --user enable
cat >>$HOME/.ipython/profile_default/ipcluster_config.py<<\EOF
c.HubFactory.ip = '*'
c.IPClusterEngines.engine_launcher_class = 'Slurm'
c.IPClusterStart.controller_launcher_class = 'Local'
EOF

