#!/usr/bin/env bash
# remove the old nvidia driver (this is not a system package install)
nvidia-uninstall -s

# install libcuda-8.0-1, which will automatically pull the corresponding nvidia-driver package
# from the ubuntu repositories (as of now this is nvidia-375)
apt-get install --yes --no-install-recommends libcuda-8.0-1

# now reload the nvidia driver
# (ignore errors, in case the machine does not have a GPU at all)
nvidia-smi || true

# put a placeholder for us to check when this script has finished executing
touch /tmp/.nvidia_placeholder
